name: Infracost Scan
# Managed by infracost ci setup v1 — re-run `infracost ci setup --pipeline` to update.

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  infracost-scan:
    runs-on: ubuntu-latest
    container: ghcr.io/infracost/ci:0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Infracost Scan
        env:
          INFRACOST_CLI_AUTHENTICATION_TOKEN: ${{ secrets.INFRACOST_API_KEY }}
        run: infracost-scanner scan --path .
